from __future__ import annotations

from typing import Protocol

from app.models import Employee, ExchangeRate, ListFilters, SalaryRecord


class EmployeeRepository(Protocol):
    def get_by_id(self, employee_id: str) -> Employee | None: ...
    def insert(self, employee: Employee) -> Employee: ...
    def update(self, employee: Employee) -> Employee: ...
    def list_page(self, filters: ListFilters) -> tuple[list[Employee], int]: ...
    def list_active(self) -> list[Employee]: ...


class SalaryRepository(Protocol):
    def insert(self, record: SalaryRecord) -> SalaryRecord: ...
    def list_for_employee(self, employee_id: str) -> list[SalaryRecord]: ...
    def get_current_for_many(self, employee_ids: list[str], today: str) -> dict[str, SalaryRecord]: ...


class FxRepository(Protocol):
    def upsert(self, rate: ExchangeRate) -> None: ...
    def list(self) -> list[ExchangeRate]: ...
